name: macOS Lint, Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build and Test default scheme
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.2"
      - name: Lint
        uses: norio-nomura/action-swiftlint@3.2.1
      - name: Build
        run: |
          xcodebuild clean build \
          -project Insights.xcodeproj \
          -scheme Insights \
          -destination 'platform=macOS' \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      - name: Run Unit Tests
        run: |
          xcodebuild test \
          -project Insights.xcodeproj \
          -scheme Insights \
          -destination 'platform=macOS' \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
